deployment:
  enabled: true
  containerPort: 8080

image:
  repository: $ECR_REGISTRY/$ECR_REPOSITORY
  tag: $IMAGE_TAG

env:
  PORT: "8080"
  AWS_REGION: eu-central-1
  ENVIRONMENT: dev
  PROVIDER_KEY: $PROVIDER
  RELOAD_RATE: 10000

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: api-dev.tradersisland.xyz
  path: "/"

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1
    memory: 1Gi
